/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.SwingUtilities;

/**
 *
 * @author oscar
 */
public class HangmanFrame extends javax.swing.JFrame {

    private ServerThread serverThread;

    /**
     * Creates new form HangmanFrame
     */
    public HangmanFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jtfHostName = new javax.swing.JTextField();
        jtfPortNumber = new javax.swing.JTextField();
        jbtnConnect = new javax.swing.JToggleButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jtfGuess = new javax.swing.JTextField();
        jbtnGuess = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        scoreNumberLabel = new javax.swing.JLabel();
        JbtnStartGame = new javax.swing.JButton();
        wrongGuesseslabel = new javax.swing.JLabel();
        wrongGuessesNumber = new javax.swing.JLabel();
        jtfView = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jbtnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jtfHostName.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        jtfHostName.setText("localhost");
        jtfHostName.setToolTipText("");

        jtfPortNumber.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        jtfPortNumber.setText("1337");

        jbtnConnect.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        jbtnConnect.setText("Connect");
        jbtnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConnectActionPerformed(evt);
            }
        });

        jInternalFrame2.setVisible(true);

        jtfGuess.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jtfGuess.setEnabled(false);

        jbtnGuess.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jbtnGuess.setText("Guess");
        jbtnGuess.setEnabled(false);
        jbtnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuessActionPerformed(evt);
            }
        });

        scoreLabel.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        scoreLabel.setText("Score:");
        scoreLabel.setEnabled(false);

        scoreNumberLabel.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        scoreNumberLabel.setText("0");
        scoreNumberLabel.setEnabled(false);

        JbtnStartGame.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        JbtnStartGame.setText("Start Game");
        JbtnStartGame.setEnabled(false);
        JbtnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnStartGameActionPerformed(evt);
            }
        });

        wrongGuesseslabel.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        wrongGuesseslabel.setText("Remaining wrong guesses:");
        wrongGuesseslabel.setEnabled(false);

        wrongGuessesNumber.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        wrongGuessesNumber.setEnabled(false);

        jtfView.setFont(new java.awt.Font("Cantarell", 0, 36)); // NOI18N
        jtfView.setText("current view");
        jtfView.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Cantarell", 0, 32)); // NOI18N
        jLabel1.setText("guess here:");

        jbtnExit.setFont(new java.awt.Font("Cantarell", 0, 30)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.setToolTipText("");
        jbtnExit.setEnabled(false);
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addComponent(jtfView)
                .addContainerGap())
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(wrongGuesseslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wrongGuessesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(0, 185, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtfGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(scoreNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JbtnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JbtnStartGame, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wrongGuesseslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrongGuessesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jtfView, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addComponent(jbtnGuess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtfHostName, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jtfPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfPortNumber)
                    .addComponent(jtfHostName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jbtnConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConnectActionPerformed
        String hostName = "localhost";
        int portNumber = 1337;
                
        
        if(!(jtfHostName.getText().equals(""))){ // if hostnamefield is "" dont care about that value, use default
            hostName = jtfHostName.getText();
        }
        if(!(jtfHostName.getText().equals(""))){
            try{
            portNumber = Integer.parseInt(jtfPortNumber.getText());
            }
            catch (java.lang.NumberFormatException nfe) {
                System.err.println("Port number must be a number between 0 and 65535");
                System.exit(1);
            }
        }
        
        jbtnConnect.setEnabled(false);
        jtfHostName.setEnabled(false);
        jtfPortNumber.setEnabled(false);
        serverThread
                = new ServerThread(HangmanFrame.this, hostName, portNumber);
        new Thread(serverThread).start();

    }//GEN-LAST:event_jbtnConnectActionPerformed

    private void JbtnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnStartGameActionPerformed
        serverThread.addMessage("startgame");
    }//GEN-LAST:event_JbtnStartGameActionPerformed

    private void jbtnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuessActionPerformed
        String guess = jtfGuess.getText();
        jtfGuess.setText("");
        if(!(guess.equals("")||guess.contains(" "))){
            serverThread.addMessage(guess);
        }
    }//GEN-LAST:event_jbtnGuessActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        serverThread.addMessage("exitgame");
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HangmanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HangmanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HangmanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HangmanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HangmanFrame().setVisible(true);
            }
        });
    }
    void connected()
    {
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                JbtnStartGame.setEnabled(true);
                jbtnExit.setEnabled(true);
                scoreLabel.setEnabled(true);
                scoreNumberLabel.setEnabled(true);
            }
        });
    }
    void gameStarted(String view, String wrongGuesses)
    {
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                JbtnStartGame.setEnabled(false);
                jbtnExit.setEnabled(false);
                wrongGuesseslabel.setEnabled(true);
                wrongGuessesNumber.setEnabled(true);
                jbtnGuess.setEnabled(true);
                jtfGuess.setEnabled(true);
                jtfView.setEnabled(true);
                jtfView.setText(view);
                wrongGuessesNumber.setText(wrongGuesses);
            }
        });
    }
    
    void sentGuess(String view, String wrongGuesses)
    {
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                jtfView.setText(view);
                wrongGuessesNumber.setText(wrongGuesses);
                
            }
        });
       }
    void gameDone(String message, String totalscore){
        
        SwingUtilities.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                jtfView.setText(message);
                scoreNumberLabel.setText(totalscore);
                JbtnStartGame.setEnabled(true);
                jbtnExit.setEnabled(true);
                jbtnGuess.setEnabled(false);
                jtfGuess.setEnabled(false);
            }
        });
    }
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnStartGame;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jbtnConnect;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGuess;
    private javax.swing.JTextField jtfGuess;
    private javax.swing.JTextField jtfHostName;
    private javax.swing.JTextField jtfPortNumber;
    private javax.swing.JTextField jtfView;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel scoreNumberLabel;
    private javax.swing.JLabel wrongGuessesNumber;
    private javax.swing.JLabel wrongGuesseslabel;
    // End of variables declaration//GEN-END:variables
}
